// ---------------------------------------------------------------------------
// Adapted from MAIN_MNIST_SINGLE_LAYER_16.cpp in
// github.com/lauriebose/Scamp5-MNIST_AREG_CNN_example (the paper's own
// reference implementation of arXiv:2004.12525, "Fully Embedding Fast
// Convolutional Networks on Pixel Processor Arrays").
//
// The convolution / ReLU / max-pool / in-pixel-FC sections below are the
// SAME algorithm as the reference (same filters=16, filter_size=4, same
// checkerboard flood-fill convolution trick, same ternary in-pixel FC via
// global_sum_sparse) -- only parameterized by NUM_GESTURES (5) instead of a
// hardcoded 10, and using gesture-blob capture (GESTURE_CAPTURE.hpp) instead
// of handwritten-digit extraction. This is NOT the old (incorrect)
// sequential-shift-and-accumulate scheme from the previous attempt -- all 16
// filters are computed in ONE parallel SIMD pass, exactly as the paper
// describes, because the reference's actual mechanism is reused unchanged.
//
// NOT compiled or run in this environment (no SCAMP5 SDK/simulator/hardware
// available here); ported for correctness against the real API and the
// reference's proven logic, unverified against real hardware.
// ---------------------------------------------------------------------------

#include <math.h>
#include <scamp5.hpp>
#include <list>
#include <string>
#include <climits>

#include "TIMING_STATS.hpp"
#include "AREG_POOLING.hpp"
#include "MISC_FUNCTIONS.hpp"
#include "GESTURE_CAPTURE.hpp"
#include "FUNCS_WEIGHT_LOADING.hpp"
#include "WEIGHTS_GESTURE_4x4_16CONVOLS_64x64INPUT.hpp"  // generated by train.py

using namespace SCAMP5_PE;

// matches the original reference's own style (a local const, not a macro --
// FUNCS_WEIGHT_LOADING.hpp has an unrelated same-named function parameter,
// so a macro here would be fragile / order-dependent)
const int filter_size = FILTER_SIZE;  // 4, from the generated weights header

extern int default_convolution_filters[];

#define final_neuron_activations_log_length 3
int final_neuron_activations_log_index = 0;
int final_neuron_activations_log[final_neuron_activations_log_length][NUM_GESTURES];
int final_neuron_activations_averages[NUM_GESTURES];

void MAIN_GESTURE_SINGLE_LAYER_16()
{
	vs_stopwatch timer;

	vs_init();

	int predictions = 0;
	int correct_predictions = 0;
	int current_prediction = 0;

	///////////////////////////////////////////////////////////////////////////////////////////////////////////
	//SETUP DISPLAYS

	const int display_size = 1;

	auto display00 = vs_gui_add_display("", 0, 0, display_size);
	auto display01 = vs_gui_add_display("", 0, display_size, display_size);
	auto display02 = vs_gui_add_display("", 0, display_size * 2, display_size, "preset_pgnr");

	auto display10 = vs_gui_add_display("", display_size, 0, display_size, "preset_pgnr");
	auto display11 = vs_gui_add_display("", display_size, display_size, display_size, "preset_pgnr");
	// bar-plot label -- gesture names instead of digits 0-9
	std::string barplot_label;
	for (int n = 0; n < NUM_GESTURES; n++) { barplot_label += " "; barplot_label += GESTURE_NAMES[n]; }
	auto display12 = vs_gui_add_display(barplot_label.c_str(), display_size, display_size * 2, display_size);

	vs_gui_set_barplot(display12, 0, 100, 15);

	bool print_timings = true;
	auto print_timings_but = vs_gui_add_button("print timings");
	vs_on_gui_update(print_timings_but, [&](int32_t new_value) {
		print_timings = true;
		predictions = 0;
		correct_predictions = 0;
	});

	int img_threshold = 100;
	vs_gui_add_slider("img_threshold", -120, 120, 100, &img_threshold);

	int grid_posx = 256 - (1 + 64 / 2), grid_posy = 64 / 2;
	int weight_grid_width = 256 / 64;

	int input_img_size = 64;
	int grid_cell_padding = 0;
	int convol_steps = NUM_FILTERS - 1;

	int input_white = 120;
	vs_gui_add_slider("input_white", -120, 120, 15, &input_white);
	int input_black = 0;

	int apply_relu = 1;
	int maxpool = 4;
	int maxpool_dirx = 0, maxpool_diry = 1;
	int maxpool_blocking = 1;

	int FC_weights_orderx = 0, FC_weights_ordery = 1;
	int FC_switch_xy = 0;

	// how large (in pixels of the 256x256 sensor) the extracted hand
	// silhouette is scaled to fill before being duplicated into the grid
	int extracted_gesture_img_size = 45;
	vs_gui_add_slider("extracted_gesture_img_size", 0, 128, 45, &extracted_gesture_img_size);

	int FC_weight_debug = -1;
	vs_gui_add_slider("FC weight debug", -1, NUM_GESTURES - 1, -1, &FC_weight_debug);

	auto load_fc_weights_button = vs_gui_add_button("load_fc_weights_button");
	vs_on_gui_update(load_fc_weights_button, [&](int32_t new_value) {
		load_FC_weights_into_grid_E(FC_weight_debug + 1, NUM_FILTERS, NUM_GESTURES, FC_layer_weights_GESTURE_4x4,
			FC_switch_xy, FC_weights_orderx, FC_weights_ordery, input_img_size, grid_posx, grid_posy, weight_grid_width, grid_cell_padding);
		scamp5_kernel_begin();
			mov(A, E);
		scamp5_kernel_end();

		load_filter_weights_into_grid_F(NUM_FILTERS, filter_size, TW_CONVOL_weights_GESTURE_4x4, input_img_size, grid_posx, grid_posy, weight_grid_width, grid_cell_padding);
		scamp5_kernel_begin();
			mov(B, F);
		scamp5_kernel_end();
	});

	int gsum_order = 0;

	int tweak;
	vs_gui_add_slider("tweak", 0, 20, 1, &tweak);

	auto slider_vxc = vs_gui_add_slider("vxc: ", 0, 4095, 2450);
	vs_on_gui_update(slider_vxc, [&](int32_t new_value) {
		vs_scamp5_configure_voltage(3, new_value);
	});

	int min_score = INT_MAX;
	int max_score = INT_MIN;

	while (true)
	{
		scamp5_get_image(F, E, vs_gui_read_slider(VS_GUI_FRAME_GAIN));

		scamp5_output_image(F, display00);
		// bright hand on dark background => white_on_black_blob = true
		// (the reference's MNIST digits are dark-on-white, hence its `false`)
		extract_gesture_blob_from_F_into_R11(true, img_threshold, extracted_gesture_img_size, grid_posx, grid_posy - 1);
		duplicate_gesture_into_grid_R10(input_img_size, weight_grid_width, grid_cell_padding);
		scamp5_kernel_begin();
			MOV(R5, R10);
		scamp5_kernel_end();
		scamp5_output_image(R5, display01);

		//////////////////////////////////////////////////////////////////////////////////////////////

		//REFRESH DUPLICATED GESTURE SILHOUETTE
		scamp5_kernel_begin();
			REFRESH(R5);
		scamp5_kernel_end();

		//REFRESH FC WEIGHTS IN AREG A AND CONVOL WEIGHTS IN B
		vs_process_message();
		vs_wait_frame_trigger();

		scamp5_load_in(E, 0);
		scamp5_load_in(50);
		scamp5_kernel_begin();
			mov(F, A);
			sub(F, F, IN);
			where(F);
				add(E, E, IN);
				add(E, E, IN);
			all();
			bus(F, A);
			sub(F, F, IN);
			where(F);
				sub(E, E, IN);
				sub(E, E, IN);
			all();
			mov(A, E);
		scamp5_kernel_end();

		scamp5_load_in(E, 0);
		scamp5_load_in(80);
		scamp5_kernel_begin();
			mov(F, B);
			sub(F, F, IN);
			where(F);
				add(E, E, IN);
				add(E, E, IN);
			all();
			bus(F, B);
			sub(F, F, IN);
			where(F);
				sub(E, E, IN);
				sub(E, E, IN);
			all();
			mov(B, E);
		scamp5_kernel_end();

		scamp5_output_image(B, display10);
		scamp5_output_image(A, display11);

		//////////////////////////////////////////////////////////////////////////////////////////////
		//PERFORM CONVOLUTION LAYER -- all NUM_FILTERS filters computed in ONE
		//parallel SIMD pass via the checkerboard flood-fill weight broadcast,
		//exactly as Section 4.2/4.3 of the paper describes. This is the part
		//the previous (incorrect) attempt did sequentially instead.

		load_DREG_into_F(DENUM::R5, input_white, input_black);
		scamp5_kernel_begin();
			MOV(R8, R5);
		scamp5_kernel_end();

		scamp5_load_in(0);
		scamp5_kernel_begin();
			mov(C, IN);
		scamp5_kernel_end();
		scamp5_load_in(40);
		scamp5_kernel_begin();
			sub(D, B, IN);
			where(D);
				MOV(R9, FLAG);
			all();
		scamp5_kernel_end();

		scamp5_load_in(F, input_white);

		int shift2 = 1;
		while (shift2--) {
			scamp5_kernel_begin();
				WHERE(R9);
				DNEWS(R9, FLAG, north);
			scamp5_kernel_end();
		}

		timer.reset();

		////////////////////////////////////////////////////////////
		//CREATE PATTERN USED TO CONSTRAIN FLOODING WHEN SPREADING FILTER WEIGHTS
		//for 4x4 grid of 64x64 computation blocks (NUM_FILTERS=16)
		scamp5_load_pattern(R1, 0, 0, 255, 192);
		scamp5_load_pattern(R2, 0, 0, 192, 255);
		scamp5_kernel_begin();
			OR(R3, R1, R2);
			NOT(R10, R3);
		scamp5_kernel_end();

		//////////////////////////////////////////////////////////////

		int weight_index = 0;
		for (int y = 0; y < filter_size; y++)
		{
			for (int x = 0; x < filter_size; x++)
			{
				if (weight_index > convol_steps)
				{
					y = filter_size;
					break;
				}

				scamp5_load_pattern(R11, 8 - weight_index / 4, 7 - weight_index % 4, 224, 224);

				scamp5_kernel_begin();
					AND(R1, R9, R11);
					MOV(R11, R1);
				scamp5_kernel_end();

				scamp5_flood(R11, R10, 0, 1);

				scamp5_kernel_begin();
					AND(R1, R8, R11);
					WHERE(R1);
						add(C, C, F);
					NOT(R1, R11);
					AND(R2, R8, R1);
					WHERE(R2);
						sub(C, C, F);
					all();
				scamp5_kernel_end();

				if (x != filter_size - 1)
				{
					scamp5_kernel_begin();
						WHERE(R8);
						DNEWS(R8, FLAG, west);
						ALL();
					scamp5_kernel_end();
				}
				else
				{
					scamp5_kernel_begin();
						WHERE(R8);
						DNEWS(R8, FLAG, east);
						ALL();
						WHERE(R8);
						DNEWS(R8, FLAG, east);
						ALL();
						WHERE(R8);
						DNEWS(R8, FLAG, east);
						ALL();
						WHERE(R8);
						DNEWS(R8, FLAG, south);
						ALL();
					scamp5_kernel_end();
				}
				weight_index++;
			}
		}

		if (print_timings) { vs_post_text("CONVOL LAYER TIME %d \n", (int)timer.get_usec()); }

		////////////////////////////////////////////////////////////////////////////////////////////////
		//PERFORM RELU -- plain zero-threshold, matches the paper exactly (Section 4.3)

		timer.reset();

		if (apply_relu)
		{
			scamp5_load_in(F, 0);
			scamp5_kernel_begin();
				where(C);
					mov(F, C);
				all();
				mov(C, F);
			scamp5_kernel_end();
		}

		////////////////////////////////////////////////////////////////////////////////////////////////
		//PERFORM MAXPOOLING

		if (maxpool > 1)
		{
			scamp5_kernel_begin();
				mov(F, C);
			scamp5_kernel_end();
			AREG_POOLING::MAX_POOL_F(maxpool - 1, maxpool_dirx == 1, maxpool_diry == 1, maxpool_blocking);
			scamp5_kernel_begin();
				mov(C, F);
			scamp5_kernel_end();
		}

		scamp5_kernel_begin();
			movx(C, C, west);
		scamp5_kernel_end();
		scamp5_kernel_begin();
			movx(C, C, north);
		scamp5_kernel_end();

		if (print_timings) { vs_post_text("RELU MAXPOOL TIME %d \n", (int)timer.get_usec()); }

		////////////////////////////////////////////////////////////////////////////////////////////////
		//PPA FC layer -- ternary weights, computed in-pixel, matches Section 5

		timer.reset();

		scamp5_kernel_begin();
			REFRESH(R6);
			REFRESH(R7);
		scamp5_kernel_end();

		//PUT FC WEIGHTS INTO DREG
		scamp5_load_in(50);
		scamp5_kernel_begin();
			mov(F, A);
			sub(F, F, IN);
			where(F);
				MOV(R6, FLAG);
			all();

			bus(F, A);
			sub(F, F, IN);
			where(F);
				MOV(R7, FLAG);
			all();
		scamp5_kernel_end();

		scamp5_load_in(F, 0);
		scamp5_kernel_begin();
			WHERE(R6);
				add(F, F, C);
			ALL();

			WHERE(R7);
				sub(F, F, C);
			ALL();
		scamp5_kernel_end();

		//PERFORM FC LAYER -- read out via global_sum_sparse, averaged over
		//`tweak` repeats x 4 quadrants (the duplicated-4x array) purely to
		//reduce analog readout noise (Section 5.1), NOT 4 different neuron
		//encodings -- all 4 quadrants hold identical duplicated data.

		int sums[NUM_GESTURES];
		for (int i = 0; i < NUM_GESTURES; i++) sums[i] = 0;
		min_score = INT_MAX;
		max_score = INT_MIN;

		for (int j = 0; j < tweak; j++)
		{
			const int quadrant_offsets[4][2] = { {0, 0}, {128, 0}, {0, 128}, {128, 128} };
			for (int q = 0; q < 4; q++)
			{
				scamp5_load_in(0);
				scamp5_kernel_begin();
					mov(F, IN);
					WHERE(R6);
						add(F, F, C);
					ALL();
					WHERE(R7);
						sub(F, F, C);
					ALL();
					mov(E, F);
				scamp5_kernel_end();
				gsum_order = (gsum_order + 1) % NUM_GESTURES;
				for (int i = 0; i < NUM_GESTURES; i++)
				{
					int n = (i + gsum_order) % NUM_GESTURES;
					int x = n % 4 - 1;
					int y = n / 4;
					sums[n] += scamp5_global_sum_sparse(E, y + quadrant_offsets[q][1], x + quadrant_offsets[q][0], 124, 124);
				}
			}
		}

		for (int i = 0; i < NUM_GESTURES; i++)
		{
			if (sums[i] > max_score) max_score = sums[i];
			if (sums[i] < min_score) min_score = sums[i];
		}

		if (print_timings) { vs_post_text("FC LAYER TIME %d \n", (int)timer.get_usec()); }

		////////////////////////////////////////////////////////////////////////////////////////////////
		//UPDATE FINAL NEURON ACTIVATIONS AND PREDICTION

		for (int n = 0; n < NUM_GESTURES; n++)
		{
			final_neuron_activations_log[final_neuron_activations_log_index][n] =
				(max_score > min_score) ? 100 * (sums[n] - min_score) / (max_score - min_score) : 0;
		}
		final_neuron_activations_log_index = (final_neuron_activations_log_index + 1) % final_neuron_activations_log_length;

		max_score = INT_MIN;
		for (int n = 0; n < NUM_GESTURES; n++)
		{
			final_neuron_activations_averages[n] = 0;
			for (int i = 0; i < final_neuron_activations_log_length; i++)
			{
				final_neuron_activations_averages[n] += final_neuron_activations_log[i][n];
			}
			final_neuron_activations_averages[n] /= final_neuron_activations_log_length;
			if (final_neuron_activations_averages[n] > max_score)
			{
				current_prediction = n;
				max_score = final_neuron_activations_averages[n];
			}
		}

		int16_t bar_values_16b[NUM_GESTURES];
		for (int n = 0; n < NUM_GESTURES; n++) { bar_values_16b[n] = final_neuron_activations_averages[n]; }
		vs_post_set_channel(display12);
		vs_post_int16(bar_values_16b, 1, NUM_GESTURES);

		vs_post_text("pred: %s\n", GESTURE_NAMES[current_prediction]);

		print_timings = false;

		if (vs_loop_counter_get() % 25 == 0) { vs_led_toggle(VS_LED_1); }
		vs_loop_counter_inc();
	}
}
